# Run during the 'gulp build' command
# Overrides these options in _config.yml

# All links in the design library will start with this baseurl
# All links in the design library will start with this baseurl
baseurl: "/jekyll-strap-sass-browser-sync-patterns"

# The url for the home page of the design library
homeurl: "/jekyll-strap-sass-browser-sync-patterns"

# Set the default layout for everything in the docs folder to _layouts/pattern.html
defaults:
  - scope:
      path: "docs"
    values:
      layout: "pattern"
  - scope:
      path: "docs/guides"
    values:
      layout: "guide"

# The list of all versions, which are referenced on the home page
versions:
  - name: 1.0.0
    url: /jekyll-strap-sass-browser-sync-patterns/docs
